version: '3.6'

services:
   db:
     image: mysql:5.7
     restart: always
     environment:
       MYSQL_ROOT_PASSWORD: somewordpress
       MYSQL_DATABASE: wordpress
       MYSQL_USER: wordpress
       MYSQL_PASSWORD: wordpress

   wordpress:
     depends_on:
       - db
     image: wordpress:latest
     ports:
       - "80:80"
     restart: always
     volumes: 
        - wpwww:/var/www/html/
        - ./:/var/www/html/wp-content/themes/notheme
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress

   cli:
     image: wordpress:cli
     volumes:
         - ./:/var/www/html/wp-content/themes/notheme
         - wpwww:/var/www/html/
     user: root
     command: >
         /bin/bash -c "
         sleep 30;
         wp core install --allow-root --url='http://localhost' --title='localhost' --admin_user='admin' --admin_password='admin' --admin_email='admin@example.org';
         wp theme activate --allow-root notheme;
         wp plugin install --allow-root wordpress-importer --activate;
         wp plugin activate --allow-root wordpress-importer
         wget https://raw.githubusercontent.com/WPTRT/theme-unit-test/master/themeunittestdata.wordpress.xml;
         wp import --allow-root themeunittestdata.wordpress.xml --authors=create;
         find /var/www/html/ -user root -exec chown 33:33 {} \;"
     depends_on:
        - wordpress
     environment:
       WORDPRESS_DB_HOST: db:3306
       WORDPRESS_DB_USER: wordpress
       WORDPRESS_DB_PASSWORD: wordpress
       WORDPRESS_DB_NAME: wordpress

volumes:
    wpwww:
        driver: local
        driver_opts:
            o: bind
            type: none
            device: $PWD/wpwww


